diesel::table! {
    /// An api key represents a personal access token for a user to authenticate API requests.
    api_key (id) {
        /// The `id` column of the `api_key` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int8,
        /// The `key` column of the `api_key` table.
        ///
        /// Its SQL type is `Bytea`.
        ///
        /// (Automatically generated by Diesel.)
        key -> Bytea,
        /// The `description` column of the `api_key` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 32]
        description -> Nullable<Varchar>,
        /// The `expires` column of the `api_key` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        expires -> Timestamptz,
        /// The `scopes` column of the `api_key` table.
        ///
        /// Its SQL type is `Array<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        scopes -> Array<Text>,
        /// The `permissions` column of the `api_key` table.
        ///
        /// Its SQL type is `Array<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        permissions -> Array<Text>,
        /// The `user_id` column of the `api_key` table.
        ///
        /// Its SQL type is `Nullable<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Nullable<Int8>,
        /// The `org_id` column of the `api_key` table.
        ///
        /// Its SQL type is `Nullable<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        org_id -> Nullable<Int8>,
        /// The `last_used_at` column of the `api_key` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        last_used_at -> Nullable<Timestamptz>,
        /// The `revoked_at` column of the `api_key` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        revoked_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    /// A downloads record represents the number of times a specific version of a package was downloaded on a particular day.
    downloads (version, day) {
        /// The `version` column of the `downloads` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        version -> Int8,
        /// The `day` column of the `downloads` table.
        ///
        /// Its SQL type is `Date`.
        ///
        /// (Automatically generated by Diesel.)
        day -> Date,
        /// The `count` column of the `downloads` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        count -> Int4,
    }
}

diesel::table! {
    /// An organization represents a group of users that can own and administer packages (from github).
    org (id) {
        /// The `id` column of the `org` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int8,
        /// The `name` column of the `org` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Varchar,
        /// The `gh_id` column of the `org` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        gh_id -> Int4,
    }
}

diesel::table! {
    /// An org_admin represents a user who has administrative privileges for a specific organization.
    org_admin (org_id, user_id) {
        /// The `org_id` column of the `org_admin` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        org_id -> Int8,
        /// The `user_id` column of the `org_admin` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Int8,
        /// The `revoked_at` column of the `org_admin` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        revoked_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    /// A package represents a collection of schema versions identified by a unique name.
    package (id) {
        /// The `id` column of the `package` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int8,
        /// The `name` column of the `package` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 128]
        name -> Varchar,
    }
}

diesel::table! {
    /// A schema_admin represents an administrator for a specific package, which can be either a user or an organization.
    schema_admin (id) {
        /// The `id` column of the `schema_admin` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int8,
        /// The `package` column of the `schema_admin` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        package -> Int8,
        /// The `user_id` column of the `schema_admin` table.
        ///
        /// Its SQL type is `Nullable<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Nullable<Int8>,
        /// The `org_id` column of the `schema_admin` table.
        ///
        /// Its SQL type is `Nullable<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        org_id -> Nullable<Int8>,
        /// The `revoked_at` column of the `schema_admin` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        revoked_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    /// A user represents an individual account with access to the registry (only github for now).
    users (id) {
        /// The `id` column of the `users` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int8,
        /// The `email` column of the `users` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        email -> Varchar,
        /// The `gh_id` column of the `users` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        gh_id -> Int4,
        /// The `gh_login` column of the `users` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        gh_login -> Varchar,
        /// The `gh_avatar` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        gh_avatar -> Nullable<Varchar>,
    }
}

diesel::table! {
    /// A version represents a specific release of a package, including metadata such as checksum, description, license, and publisher information.
    version (id) {
        /// The `id` column of the `version` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int8,
        /// The `package` column of the `version` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        package -> Int8,
        /// The qualified version follows semantic versioning (semver) format, e.g., "1.0.0".
        #[max_length = 32]
        qualified_version -> Varchar,
        /// The `checksum` column of the `version` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        checksum -> Varchar,
        /// The `description` column of the `version` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 1024]
        description -> Nullable<Varchar>,
        /// The `homepage` column of the `version` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 128]
        homepage -> Nullable<Varchar>,
        /// The `license` column of the `version` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        license -> Varchar,
        /// The `readme` column of the `version` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        readme -> Varchar,
        /// The `repository` column of the `version` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        repository -> Varchar,
        /// The `keywords` column of the `version` table.
        ///
        /// Its SQL type is `Array<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        keywords -> Array<Text>,
        /// The `created_at` column of the `version` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
        /// The `yanked_at` column of the `version` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        yanked_at -> Nullable<Timestamptz>,
        /// The `publishing_org_id` column of the `version` table.
        ///
        /// Its SQL type is `Nullable<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        publishing_org_id -> Nullable<Int8>,
        /// The `publishing_user_id` column of the `version` table.
        ///
        /// Its SQL type is `Nullable<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        publishing_user_id -> Nullable<Int8>,
    }
}

diesel::joinable!(api_key -> org (org_id));
diesel::joinable!(api_key -> users (user_id));
diesel::joinable!(downloads -> version (version));
diesel::joinable!(org_admin -> org (org_id));
diesel::joinable!(org_admin -> users (user_id));
diesel::joinable!(schema_admin -> org (org_id));
diesel::joinable!(schema_admin -> package (package));
diesel::joinable!(schema_admin -> users (user_id));
diesel::joinable!(version -> org (publishing_org_id));
diesel::joinable!(version -> package (package));
diesel::joinable!(version -> users (publishing_user_id));

diesel::allow_tables_to_appear_in_same_query!(
    api_key,
    downloads,
    org,
    org_admin,
    package,
    schema_admin,
    users,
    version,
);
